server:
  context-path: /
  port: 8083
  tomcat:
    uri-encoding: utf-8
web:
  basePath: D:/XKJS/


spring:
  mvc:
    date-format: yyyy-MM-dd
    static-path-pattern: /**
  messages:
    basename: i18n.login
  resources:
    static-locations: "classpath:/META-INF/resources/,classpath:/resources/,\
    classpath:/static/,classpath:/public/,file:${web.basePath}"
  datasource:
    url: jdbc:oracle:thin:@222.204.6.175:8085/orcl
    username: academic
    password: xkjs409
    driver-class-name: oracle.jdbc.OracleDriver
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aca.springboot.entities


#持久化日志进入调试模式
logging:
  level:
    com.aca.springboot.mapper: debug



